version: "2"

services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  minelev_micro_auth_ldap:
    image: telemark/micro-auth-ldap
    container_name: minelev_micro_auth_ldap
    env_file: envs/ldap.env
    restart: always
    ports:
      - "82:8080"
    depends_on:
      - nginx_proxy

  minelev_webserver:
    image: telemark/minelev-web
    container_name: minelev_webserver
    env_file: envs/minelev.env
    restart: always
    cpu_shares: 512
    mem_limit: 1000000000
    ports:
      - "85:3000"
    depends_on:
      - minelev_micro_buddy
      - minelev_micro_logs
      - minelev_micro_auth_ldap
      - nginx_proxy
      - minelev_buddy_api

  minelev_micro_logs:
    container_name: minelev_micro_logs
    image: telemark/minelev-logs
    env_file: envs/logs.env
    restart: always
    ports:
      - "86:3000"

  minelev_micro_buddy:
    container_name: minelev_micro_buddy
    image: telemark/minelev-buddy
    env_file: envs/buddy.env
    restart: always
    ports:
      - "84:3000"

  minelev_log:
    image: mongo:3.2.9
    container_name: minelev_log
    volumes:
      - /mongo/minelev2/logs:/data/db
    ports:
      - "27017:27017"

  minelev_buddy_api:
    image: telemark/buddy-minelev-api
    container_name: minelev_buddy_api
    env_file: envs/buddy-api.env
    ports:
      - "87:3000"
