version: "2"

services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  minelev_micro_auth_ldap:
    image: telemark/micro-auth-ldap
    container_name: minelev_micro_auth_ldap
    env_file: envs/ldap.env
    restart: always
    depends_on:
      - nginx_proxy

  minelev_webserver:
    image: telemark/minelev-web
    container_name: minelev_webserver
    env_file: envs/minelev.env
    restart: always
    depends_on:
      - minelev_micro_buddy
      - minelev_micro_logs
      - minelev_micro_auth_ldap
      - nginx_proxy
      - minelev_buddy_api

  minelev_micro_logs:
    container_name: minelev_micro_logs
    image: telemark/minelev-logs
    env_file: envs/logs.env
    restart: always

  minelev_micro_buddy:
    container_name: minelev_micro_buddy
    image: telemark/minelev-buddy
    env_file: envs/buddy.env
    restart: always

  minelev_log:
    image: mongo:3.2.9
    container_name: minelev_log
    env_file: envs/mongo.env
    restart: always
    volumes:
      - /mongo/minelev2/logs:/data/db

  minelev_buddy_api:
    image: telemark/buddy-minelev-api
    container_name: minelev_buddy_api
    restart: always
    env_file: envs/buddy-api.env
